# Generated by Django 2.2.5 on 2021-07-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(default=False, max_length=20)),
                ('discp', models.TextField(blank=True)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('year', models.CharField(default='2018', max_length=20)),
                ('degree', models.CharField(default='BTech', max_length=100)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('department', models.CharField(default='Civil', max_length=100)),
            ],
        ),
    ]
