# Generated by Django 3.2 on 2021-08-09 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_no', models.IntegerField(default=0)),
                ('mentor_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(default=False, max_length=20)),
                ('discp', models.TextField(blank=True)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('year', models.CharField(default='2018', max_length=20)),
                ('degree', models.CharField(default='BTech', max_length=100)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('department', models.CharField(default='Civil', max_length=100)),
                ('maxmentees', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('available', models.BooleanField(default=True)),
                ('maxscore', models.FloatField(default=0.0)),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpi', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=12)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
        ),
    ]
