# Generated by Django 3.2 on 2021-08-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210809_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='city',
        ),
        migrations.AddField(
            model_name='mentor',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
