# Generated by Django 2.2.5 on 2021-08-06 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0003_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='favourites',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpi', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=12)),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to='registration.Mentor')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile')),
            ],
        ),
    ]
