# Generated by Django 2.2.5 on 2021-08-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210807_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='favourites',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='registration.Mentor'),
        ),
    ]
