# Generated by Django 3.2 on 2021-08-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210815_1521'),
        ('registration', '0005_remove_profile_suggestions'),
    ]

    operations = [
    ]
