# Generated by Django 2.2.5 on 2021-08-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210807_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='maxmentees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentor',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
