# Generated by Django 3.2.5 on 2021-08-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_merge_20210815_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='hostel',
        ),
        migrations.AddField(
            model_name='mentor',
            name='city',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
