# Generated by Django 2.2.5 on 2021-08-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210807_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='maxscore',
            field=models.FloatField(default=0.0),
        ),
    ]
